### ISSUE TITLE
Cannot find proj.db

### ISSUE THREAD

**Issue by dabreegster** [frewsxcv/rgis#44]
Hi! I successfully built this on Ubuntu, but running crashes:

```
2022-01-29T15:52:56.470241Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1    
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

2022-01-29T15:52:56.535337Z  INFO bevy_render::renderer: AdapterInfo { name: "Quadro T2000", vendor: 4318, device: 8120, device_type: DiscreteGpu, backend: Vulkan }
2022-01-29T15:52:56.651153Z  INFO time_logger: Opening file: "ltn_downtown_brooklyn.geojson": started
2022-01-29T15:52:56.651171Z  INFO time_logger: Opening file: "ltn_downtown_brooklyn.geojson": done (7.289µs)
2022-01-29T15:52:56.651177Z  INFO time_logger: Parsing file: "ltn_downtown_brooklyn.geojson": started
proj_create: Cannot find proj.db
proj_create: no database context specified
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/dabreegster/.cargo/git/checkouts/rgis-d37e887aa872006b/24f69cd/geo-srs/src/lib.rs:14:80
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-01-29T15:52:56.683539Z  INFO time_logger: Parsing file: "ltn_downtown_brooklyn.geojson": done (32.355321ms)
2022-01-29T15:52:56.683553Z  INFO time_logger: Converting to geo-types: "ltn_downtown_brooklyn.geojson": started
2022-01-29T15:52:56.684572Z  INFO time_logger: Converting to geo-types: "ltn_downtown_brooklyn.geojson": done (1.016532ms)
2022-01-29T15:52:56.684577Z  INFO time_logger: Adding new layer: "ltn_downtown_brooklyn.geojson": started
2022-01-29T15:52:56.684688Z  INFO time_logger: Reprojecting: started
proj_create: Cannot find proj.db
proj_create: no database context specified
thread 'Compute Task Pool (6)' panicked at 'called `Option::unwrap()` on a `None` value', /home/dabreegster/.cargo/git/checkouts/rgis-d37e887aa872006b/24f69cd/geo-srs/src/lib.rs:67:80
```

I'm not sure where it's looking for `proj.db`, but I have `/usr/share/proj/proj.db`. I thought the Rust `proj` crate statically links everything. I tried running with `strace` to see where it's looking for this file, but I didn't see any system calls mentioning it. Let me know if I can help debug further!

**Comment by michaelkirk** [comment]
>  thought the Rust proj crate statically links everything. 

I haven't looked into how rgis is using proj, but just wanted to say that the proj crate will attempt to use the system proj rather than building it's own.

You can force proj-sys to build proj by passing proj-sys the "bundled_proj" feature.

**Comment by frewsxcv** [comment]
rgis now uses proj4rs, so this should no longer be an issue
